#***************************TRANSLATOR OF ONE LANGAUGE TO ANOTHER LANGUAGE**********************************************
#HERE WE USE GOOGLE TRANSLATE LIBRARY FOR TRANSLATE WORDS INTO ANOTHER LANGUAGE.

#AFTER IMPORTING TRANSLATOR LIBRARY FROM THE GOOGLE TRANS LIBRARY.
from googletrans import Translator

#HERE WE USE A TRANSLATOR FUNCTION OF TRANSLATORY LIBRARY.
translator=Translator()

#HERE WE GIVE INPUT IN THE TERMINAL FOR CONVERTING THE WORDS.
words=input("Enter the words:")

#IN THIS IT TAKE OUTPUT FROM THE OUTPUT FUNCTION AND ALSO SELECT WHICH LANGUAGE IS USED FOR CONVERTNG TEXT FROM THE DESTINATION FUNCTION .
output= translator.translate(words, dest="HI")

#FINALLY PRINT THE OUTPUT IN THE TERMINAL.
print(output.text)